config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books, only: [:show, :edit, :index, :update, :create, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :index, :update]
  root to: 'homes#top'

  get "home/about" => "homes#about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  
  validates :user_id, uniqueness: {scope: :book_id}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, length:{minimum:2, maximum:20}, uniqueness: true
  validates :introduction, length:{maximum:50}

  has_one_attached :profile_image

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @book_comment.book_id = book.id
    if @book_comment.save
      redirect_to book_path(book)
    else
      @book_new = Book.new
      @book = Book.find(params[:book_id])
      render "books/show"
    end
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_book, only: [:edit, :update]
  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_book
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    # favorite = Favorite.new(book_id: book.id, user_id: current_user.id)
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    # favorite = Favorite.find_by(book_id: book.id, user_id: current_user.id)
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :is_matching_login_user, only: [:edit, :update]
  def show
    @book = Book.new

    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @book = Book.new
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

      <%= form_with model: @book do |f| %>
        <% if @book.errors.any? %>
          <div id="error_explanation">
            <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class:"form-control book_title" %>
        </div>
        <div class="form-group">
          <%= f.label :body, "Opinion" %>
          <%= f.text_area :body, class:"form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class:"btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book) %> |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user_info', book: @book, user: current_user %>

    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image(80, 80) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book)%></td>
              <td><%= book.body %></td>
              <% if book.favorited_by?(current_user) %>
                <td >
                  <%= link_to book_favorites_path(book), class: "text-danger", method: :delete do %>
                    <i class="fas fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                </td>
              <% else %>
                <td>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    <i class="fas fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                </td>
              <% end %>
              <td>コメント数：<%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user_info', book: @book_new, user: @book.user %>

    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user) do %>
                <%= image_tag @book.user.get_profile_image(80, 80) %>
                <br><%= @book.user.name %>
              <% end %>
            </td>
            <td><%= link_to @book.title, book_path(@book)%></td>
            <td><%= @book.body %></td>
            <% if @book.favorited_by?(current_user) %>
              <td >
                <%= link_to book_favorites_path(@book), class: "text-danger", method: :delete do %>
                  <i class="fas fa-heart"></i><%= @book.favorites.count %>
                <% end %>
              </td>
              <% else %>
              <td>
                <%= link_to book_favorites_path(@book), method: :post do %>
                  <i class="fas fa-heart"></i><%= @book.favorites.count %>
                <% end %>
              </td>
            <% end %>
            <td>コメント数：<%= @book.book_comments.count %></td>
            <% if @book.user.id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-danger" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <table>
        <% @book.book_comments.each do |book_comment| %>
        <tr>
          <td>
            <%= image_tag book_comment.user.get_profile_image(80,80) %><br>
            <%= link_to book_comment.user.name, user_path(book_comment.user) %>
          </td>
          <td>
            <%= book_comment.comment %>
          </td>
          <td>
            <% if book_comment.user.id == current_user.id %>
              <%= link_to "Destroy", book_book_comment_path(@book, book_comment), method: :delete, class: "btn btn-sm btn-danger" %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
      <% if @book_comment.errors.any? %>
        <div id="error_explanation">
          <h3><%= @book_comment.errors.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% @book_comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div>
        <%= form_with model: [@book, @book_comment] do |f| %>
          <%= f.text_area :comment, rows: '5', class: "form-control" %>
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers!</strong></h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to
      <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>

        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/9f8a6566f1.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse" id="navbarNavDropdown" style="">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
                  <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, class: "nav-link text-light" do %>
                  <i class="fas fa-users"></i> Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, class: "nav-link text-light" do %>
                  <i class="fas fa-book-open"></i> Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                  <i class="fas fa-sign-out-alt"></i> Log out
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path, class: "nav-link text-light" do %>
                  <i class="fas fa-home"></i> Home
                  <% end %>
                </li>
                <li>
                  <%= link_to home_about_path, class: "nav-link text-light" do %>
                  <i class="fas fa-link"></i> About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                  <i class="fas fa-user-plus"></i> Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                  <i class="fas fa-sign-in-alt"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div>
      <%= flash[:notice] %>
    </div>


    <main>
      <%= yield %>
    </main>

  </body>
</html>

app/views/users/_user_info.html.erb
<h2>User info</h2>
<%= image_tag user.get_profile_image(100, 100) %>
<table class="table">
  <tbody>
    <tr>
  	  <th>name</th>
  	  <th><%= user.name %></th>
    </tr>
    <tr>
  	  <th>introduction</th>
  	  <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<div class="row">
  <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
  <i class="fas fa-user-cog"></i>
  <% end %>
</div>
<h2 class="mt-3">New book</h2>
<%= form_with model: book do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class:"form-control book_title" %>
  </div>
  <div class="form-group">
    <%= f.label :body, "Opinion" %>
    <%= f.text_field :body, class:"form-control book_title" %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Book", class:"btn btn-success" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model: @user do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <label for="user_name">Name</label>
        <%= f.text_field :name, class:"form-control name"%>
      </div>
     <div class="form-group">
        <label for="user_image">Image</label>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: "image/*" %>
      </div>
      <div class="form-group">
        <label for="user_introduction">Introduction</label>
        <%= f.text_field :introduction, class:"form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update User", class: "btn btn-secondary" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'user_info', book: @book, user: current_user %>

    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(80, 80) %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'user_info', book: @book, user: @user %>

    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image(80, 80) %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
              <% if book.favorited_by?(current_user) %>
                <td >
                  <%= link_to book_favorites_path(book), class: "text-danger", method: :delete do %>
                    <i class="fas fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                </td>
                <% else %>
                <td>
                  <%= link_to book_favorites_path(book), method: :post do %>
                    <i class="fas fa-heart"></i><%= book.favorites.count %>
                  <% end %>
                </td>
              <% end %>
              <td>コメント数：<%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>